### ISSUE TITLE
YouTube Black Background - Broken sidebar and mixes

### ISSUE THREAD

**Issue by ghost** [fxolan/userscripts#4]
I've been using your YouTube black background userscript for quite a while, and I've noticed that there are two issues.

Mixes on the home page/recommended appear as black without any mix title, thumbnail, outline, etc.

Extending the sidebar on a video makes the entire site black.

Sorry for potentially bugging you, but I hope this gets fixed!

**Comment by AbdurazaaqMohammed** [comment]
Thanks for reporting, I post a new version, it should be fixed

https://github.com/AbdurazaaqMohammed/userscripts/blob/main/theme/youtube-black-background.user.js

**Comment by ghost** [comment]
Thank you! It works!
